name: CI/CD for Quiz App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Install Node.js 20 (required for JavaScript actions)
        run: |
          set -euo pipefail
          apt-get update -y
          apt-get install -y ca-certificates curl gnupg
          mkdir -p /etc/apt/keyrings
          curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
          echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" > /etc/apt/sources.list.d/nodesource.list
          apt-get update -y
          apt-get install -y nodejs
          node -v
          npm -v

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install prerequisites (unzip)
        run: |
          apt-get update -y
          apt-get install -y unzip

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Init Terraform
        working-directory: Iac-deployment
        run: terraform init

      - name: Validate Terraform
        working-directory: Iac-deployment
        run: terraform validate

      - name: Run Terraform apply
        working-directory: Iac-deployment
        run: terraform apply -auto-approve
